---
- name: "restart rsyslog"
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: "restart haproxy"
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: yes
